version: "3.1"

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./api:/app"
    ports:
      - "5000:3000"
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
